
DROP TABLE IF EXISTS CFG_TABLE;

CREATE TABLE CFG_TABLE(
TBL_ID BIGINT IDENTITY(1,1) NOT NULL,
TBL_NAME VARCHAR(100),
TBL_DESC VARCHAR(255), --表名称
PKG_NAME VARCHAR(255), --包名
CLS_NAME VARCHAR(255),  --类名
CONSTRAINT PK_CFG_TABLE PRIMARY KEY CLUSTERED (TBL_ID)
);


DROP TABLE IF EXISTS CFG_TABLECOL;

CREATE TABLE CFG_TABLECOL(
COL_ID BIGINT IDENTITY(1,1) NOT NULL,
TBL_ID BIGINT,
COL_NAME VARCHAR(100),     --列名称
CLS_FIELDNAME VARCHAR(100), --类属性名
COL_PRIMARY CHAR(1),  --标识是否为主键
COL_GENSTRA CHAR(1),  --主键生成策略
COL_SEQNAME VARCHAR(255), --序列名称
COL_NULLABLE CHAR(1),
COL_TYPE VARCHAR(255),
CLS_TYPE VARCHAR(255),
COL_LEN  INT,
COL_DEFVAL VARCHAR(255),
COL_DESC VARCHAR(255),
CONSTRAINT PK_CFG_TABLECOL PRIMARY KEY CLUSTERED (COL_ID)
);

DROP TABLE IF EXISTS CFG_RELATION;

CREATE TABLE CFG_RELATION(
REL_ID BIGINT IDENTITY(1,1) NOT NULL,
REL_LEFT BIGINT,        --关系左表
REL_RIGHT BIGINT,       --关系右表
REL_DESC VARCHAR(255),
TYPE_LEFT  CHAR(1),     --*, 1
TYPE_RIGHT CHAR(1),     --*, 1
REL_FETCHTYPE CHAR(1),
CONSTRAINT PK_CFG_RELATION PRIMARY KEY CLUSTERED (REL_ID)
);

DROP TABLE IF EXISTS CFG_RELJOIN;

CREATE TABLE CFG_RELJOIN(
JOIN_ID BIGINT IDENTITY(1,1) NOT NULL,
REL_ID  BIGINT,
COL_LEFT  BIGINT,      --左表连接字段
COL_RIGHT BIGINT,      --右表连接字段
CONSTRAINT PK_CFG_RELJOIN PRIMARY KEY CLUSTERED (JOIN_ID)
);

