
DROP TABLE IF EXISTS CFG_TABLE;

CREATE TABLE CFG_TABLE(
TBL_ID BIGINT NOT NULL,
TBL_NAME VARCHAR(100),
TBL_DESC VARCHAR(255), --表名称
PKG_NAME VARCHAR(255), --包名
CLS_NAME VARCHAR(255),  --类名
CONSTRAINT PK_CFG_TABLE PRIMARY KEY CLUSTERED (TBL_ID)
);


DROP TABLE IF EXISTS CFG_TABLECOL;

CREATE TABLE CFG_TABLECOL(
COL_ID BIGINT NOT NULL,
TBL_ID BIGINT,
COL_NAME VARCHAR(100),     --列名称
CLS_PROPNAME VARCHAR(100), --类属性名
COL_PRIMARY CHAR(1),
COL_DESC VARCHAR(255),
CONSTRAINT PK_CFG_TABLECOL PRIMARY KEY CLUSTERED (COL_ID)
);

DROP TABLE IF EXISTS CFG_RELATION;

CREATE TABLE CFG_RELATION(
REL_ID BIGINT NOT NULL,
REL_LEFT BIGINT,        --关系左表
REL_RIGHT BIGINT,       --关系右表
REL_DESC VARCHAR(255),
LEFT_TYPE  CHAR(1),     --*, 1
RIGHT_TYPE CHAR(1),     --*, 1
CONSTRAINT PK_CFG_RELATION PRIMARY KEY CLUSTERED (REL_ID)
);

DROP TABLE IF EXISTS CFG_RELJOIN;

CREATE TABLE CFG_RELJOIN(
JOIN_ID BIGINT NOT NULL,
REL_ID  BIGINT,
LEFT_COL  BIGINT,      --左表连接字段
RIGHT_COL BIGINT,      --右表连接字段
CONSTRAINT PK_CFG_RELJOIN PRIMARY KEY CLUSTERED (JOIN_ID)
);

